; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    bodmer/TFT_eSPI

build_flags =
    -D USER_SETUP_LOADED=1

    ; Driver
    -D ST7789_DRIVER

    ; Display size
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240

    ; SPI Pins (CHANGE if needed)
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4

    ; Backlight
    -D TFT_BL=15
    -D TFT_BACKLIGHT_ON=HIGH

    ; Color order (important for IPS)
    -D TFT_RGB_ORDER=TFT_BGR

    ; SPI speed
    -D SPI_FREQUENCY=40000000

    ; Fonts (optional)
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_GFXFF